# Generated by Django 5.1.7 on 2025-04-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingrecord',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
    ]
